### ISSUE TITLE
Processor: onSubscribe requirement, error handling?

### ISSUE THREAD

**Issue by akarnokd** [reactive-streams/reactive-streams-jvm#227]
According to the spec, a Processor must obey the event semantics of ```onSubscribe onNext* (onError | onComplete)?``` on its Subscriber side, but when I want to use it as an event source (such as in GUI event observable) there is no upstream that could provide such ```Subscription```. In this case, should I set a no-op subscription on the processor?

The second thing what's unclear for me is if a subscriber to a processor throws in its ```onNext``` method, should such error be isolated from other subscribers? For example, a GUI code is publishing mouse movements to multiple subscribers. If one errors out, only that instance should be evicted. Rule 2.13 has such implications but maybe it is worth reinforcing it in a new 4.3 rule, i.e., 

"If a subscriber doesn't return normally because any of its ```onNext```, ```onError``` or ```onComplete``` methods throw, such exception MUST be isolated from other subscribers and the subscription MUST be cancelled. If ```onNext``` threw, the exception should be propagated downstream via ```onError```."

If ```onError``` or ```onComplete``` threw, where should these exceptions go? Can't send them back down via ```onError```. Perhaps a rule/clause stating that such very exceptional cases "may be handled in a fashion that is adequate for the runtime environment", i.e., with some global uncaught exception handler.

Rule 2.8 states that after calling ```cancel```, a subscriber should expect some ```onNext``` calls. Should it also expect ```onError``` and ```onComplete``` events as well?

**Comment by ktoso** [comment]
Hello @akarnokd!
Welcome to the reactive streams initiative :-) Allow me to have a stab at your questions:

1) If there's not upstream, you're a `Publisher` not a `Processor` - no need to handle any upstream if there is none. That is a "source of data" is a `Publisher` (we even use such naming in akka-streams by the way).

2) Throwing inside any of these methods you mention (expect an `NullPointerException`) is a spec violation, and as such valid implementations must not allow these to happen. For example, in akka streams we contain user exceptions and allow to handle these internally (by resuming / restarting or aborting the stream processing). An adequate way of handling this may for example be logging error statements about this etc. It depends on what your impl is able to do. This suggestion is covered in Rule `2.13` - `[...] the caller MUST raise this error condition in a fashion that is adequate for the runtime environment.`.

3) No. `cancel` is inherently "racy", as there may already be some "onNext signals in flight when you signal the cancellation" - remember we're talking about asynchronous communication here. The same is not true for `onComplete` and `onError`, they are the last signal that is to be signalled downstream - there is not race between onNext and onComplete arriving, because the source is the same Publisher (and concurrent signalling is illegal - `1.3`)

Hope this helps!

**Comment by viktorklang** [comment]
Konrad,  there is a race between cancel() by the Subscriber and
onNext/onComplete/onError signalled by the Publisher.

-- 
Cheers,
√

**Comment by akarnokd** [comment]
I've implemented an ```AsyncProcessor``` (~```AsyncSubject``` in RxJava) in a way that it doesn't require a subscription be set, but if one is set, it requrests ```Long.MAX_VALUE```. This way, the AsyncProcessor can be directly used, but clearly violates §1.9 when ```onNext```, ```onError``` and ```onComplete``` is called. I've also implemented a ```DelayedSubscription```, which accumulates ```request()``` and ```cancel()``` calls until a real ```Subscription``` is set on it, to support the Subscriber-side event serialization. This class can also be the default subscription for ```Processor```s but at the cost of ~40 bytes of extra memory per instance. (It would be nice if §4.x would give an exception to the event delivery semantics: ```onSubscribe? onNext* (onError | onCompleted)?```)

**Comment by viktorklang** [comment]
Hi @akarnokd,

I'm not sure what you mean, you can definitely attach a Subscriber to a Processor before the Processor itself is attached as a Subscriber?

Could you elaborate?

**Comment by akarnokd** [comment]
Sure. The following use is illegal because of §1.9:

```java
MyProcessor mp = new MyProcessor()

mp.subscribe(new MySubscriber());

mp.onNext(1);
```

**Comment by viktorklang** [comment]
Of course, this is by design, but the following is legal:

~~~java
MyProcessor mp = new MyProcessor()
mp.subscribe(new MySubscriber());
~~~

**Comment by akarnokd** [comment]
Yes, but in order to call ```onNext``` on ```mp```, one has to first get a ```Subscription``` somewhere and call ```mp.onSubscribe```. Otherwise, a ```Processor``` can be only used as a dispatcher for another ```Producer```, never on its own if it wants to conform with the spec.

**Comment by viktorklang** [comment]
Yes, that's correct—the only thing that should call onNext is a Publisher.

If you want to have some sort of "manual emitter" you're better off creating a Publisher that exposes methods for emissions and a protocol for how to handle the case where there is no subscription or demand.

Worth keeping in mind Reactive Streams is a spec for the interaction between Publishers and Subscribers—it is not an end-user API.

**Comment by akarnokd** [comment]
> If you want to have some sort of "manual emitter" you're better off creating a Publisher that exposes methods for emissions and a protocol for how to handle the case where there is no subscription or demand.

Yes, this is what's likely to happen with RxJava 2.0; we keep our Subject and relax some RS requirements when our components interact with each other (but not with the outside world).

**Comment by viktorklang** [comment]
@akarnokd That sounds fair enough :)
