### ISSUE TITLE
Clarification on SubscriberBlackboxVerification.createElement

### ISSUE THREAD

**Issue by purplefox** [reactive-streams/reactive-streams-jvm#231]
Hello folks,

I'm looking at getting the TCK working against Vert.x.

Currently trying to extend SubscriberBlackboxVerification, and I'm not sure how to implement the createElement() method.

@Override
  public Buffer createElement(int i) {
    return ??
  }

In particular I can't figure out what the parameter i represents (I did read the javadoc but none the wiser)... and how it relates to the return value. (We are using streams of Buffer throughout the TCK tests - Buffer is a Vert.x class)

Any pointers?

**Comment by ktoso** [comment]
Thanks for your feedback (very valuable as a fresh pair of eyes)!
I'll see how I can improve the comments and docs around this.

Here's a short answer right away though:
Since in order to test a `Subscriber` we need "some publisher". In older versions of the TCK implementers had to provide the publisher as well, to "drive" the test. Currently the publisher (an asynchronous one) is provided. However (here createElement comes into play), there may exist subscribers which only make sense for some weird type of element - for example if I'm a "FileSubscriber" and have implemented it strictly to work with bytearrays. The createElement method allows such Subscribers to be given the type of element they need. The incoming `i` parameter means "which element".

Most implementation scan simply: 

```java
// I'm testing an Integer subscriber:
/* .. */ extends SubscriberBlackboxVerification<Integer> { 
  @Override public Subscriber<Integer> createSubscriber() { } // my Integer subscriber
  @Override public Integer createElement(int i) { return i; } // I create elements of the type it wants
}
```

You may find tests in the examples project useful, here's a subscriber test: https://github.com/reactive-streams/reactive-streams-jvm/blob/master/examples/src/test/java/org/reactivestreams/example/unicast/SyncSubscriberTest.java

**Comment by purplefox** [comment]
Thanks

**Comment by viktorklang** [comment]
Should this be closed?

**Comment by viktorklang** [comment]
Ping @ktoso

**Comment by ktoso** [comment]
How about closing it with such additional wording: https://github.com/reactive-streams/reactive-streams-jvm/pull/250

Tim's input has been valuable here, if he wasn't sure how to use it, others might as well. I hope the additional paragraph helps in that perspective.

**Comment by viktorklang** [comment]
@ktoso Sounds good to me, I've commented on that PR.
