### ISSUE TITLE
Can Subscriber assume all methods are externally synchronized?

### ISSUE THREAD

**Issue by maxwindiff** [reactive-streams/reactive-streams-jvm#274]
Rule 1.3 says "onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled sequentially (no concurrent notifications)." Does it imply these methods are externally synchronized? Say if I have this `Subscriber`:

```java
class MySubscriber implements Subscriber<String> {
    private final StringBuilder sb = new StringBuilder();
    public void onNext(String msg) {
        sb.append(msg); // here
    }
    ...
}
```

Is it safe to access the `StringBuilder` without synchronization?

And does the jsr166 version amount to the same thing?
> http://gee.cs.oswego.edu/dl/jsr166/dist/docs/java/util/concurrent/Flow.Subscriber.html 
> public static interface Flow.Subscriber<T>
> A receiver of messages. The methods in this interface are invoked in strict sequential order for each Flow.Subscription.

**Comment by davidmoten** [comment]
I think you are fine to do that. Those methods are signalled sequentially.
The chain of operators upstream of the Subscriber may mean that the methods
are called from different threads over time (which would affect ThreadLocal
fields if you had them) but the necessary memory barriers are put in place
by SafeSubscriber so that synchronization has occurred by the time those
methods are called.

I don't know about the Flow question.

**Comment by davidmoten** [comment]
oops sorry @maxwindiff , thought this was an RxJava issue!

**Comment by viktorklang** [comment]
The Publisher must make sure to have the appropriate barriers in place if
it signals from different (but not concurrent) threads, and the Subscriber
must have the appropriate barriers in place when/if it processes it's
signals on different (but not concurrent) threads.

Since j.u.c.Flow is a mirror of RS same rules apply.

-- 
Cheers,
√

**Comment by akarnokd** [comment]
I must correct @davidmoten, it is the `SerializedSubscriber` which does the thread-safe serialization in RxJava. 

I'm a bit puzzled about §2.2 and this question. In my reading it implies that all `Publisher`s have to introduce asynchrony adaptively, but introducing async work without the developers knowledge or consent IMO is a bad thing. In RxJava, we have the `observeOn()` for this: if the developer feels the processing is going to be slow, it can apply the operator to the stream.

The second thing, many questions similar these imply to me that many try to implement their own push-pull framework on top of RS instead of picking an existing implementation. Is my feeling right?

**Comment by maxwindiff** [comment]
@davidmoten no worries!

@viktorklang So if I understand correctly, since Publisher used the right barriers and never signals the Subscriber concurrently, the Subscriber can assume it's externally synchronized and don't have to worry about thread safety (unless, of course, it handles the signals on different threads).

Should "Publishers must make sure to have the appropriate barriers in place" be added to the spec? This is important information for implementors.

**Comment by davidmoten** [comment]
@akarnokd ta for correction, memory failure!

**Comment by viktorklang** [comment]
The spec is written to allow for both sync and async publishers and
subscribers with the caveat that they may not blow the stack nor hold the
caller thread hostage.

I would love it if you have time to elaborate how you come to your
conclusion,

Thanks!

-- 
Cheers,
√

**Comment by viktorklang** [comment]
@maxwindiff Hi Max, what's the status here?

**Comment by maxwindiff** [comment]
Yep I'm good now (will assume externally synchronized). Closing this.

**Comment by davidmoten** [comment]
Can we get an answer on this from @maxwindiff ?

>Should "Publishers must make sure to have the appropriate barriers in place" be added to the spec? This is important information for implementors.

I'm not convinced after this discussion that from the specs as they are that the external synchronization that @maxwindiff asks about is guaranteed. It's possible that 1.3 implies a happens-before relationship is in place and hence synchronization happens but I'm not sure it's that tight.

**Comment by viktorklang** [comment]
@davidmoten 

1:3 says that a Publisher must not make concurrent notifications, i.e. have multiple threads at the same time signalling the same Subscriber. This is to prevent every Subscriber from having to parry for that.

2:11 says that a Subscriber, if processing its signals asynchronously must provide appropriate *happens-before* guarantees between the signal being sent and the signal being processed.

What this means in practice:

Synchronous Publisher == SP
Asynchronous Publisher == AP
Synchronous Subscriber == SS
Asynchronous Subscriber == AS

happens-before-relationship == HBR

For SP + SS == there are no barriers needed because the Publisher will not jump threads and the Subscriber won't either, everything gets executed on the calling thread.

For AP + AS == AP will need to provide HBR for *itself* to make sure that it is safely published between threads, AS will need to provide HBR between the signals being sent and the signals being processed.

For SP + AS == SP will piggyback on the HBR provided by the AS as the AS will need to provide HBR between the signals being sent and the signals being processed.

For AP + SS == SS will piggyback on the HBR provided by the AP as the AP will need to provide HBR for *itself* to make sure that it is safely published between threads.



Does that make sense?

**Comment by davidmoten** [comment]
Thanks @viktorklang for detailed explanation, makes sense.The conversation above made no reference to 2:11 so I missed that,

**Comment by maxwindiff** [comment]
It seems there is no rule that directly states "AP will need to provide HBR for itself". Is it correct to say that for an AP to work correctly (potentially across multiple threads), it have to have to have proper synchronization for itself, so the HBR comes from that?

**Comment by viktorklang** [comment]
Hi Max,

Yes, it is implied but not directly stated.  I'll propose a clarification
to the rule that governs it to aid future readers.

-- 
Cheers,
√

**Comment by kjkrum** [comment]
@akarnokd 
>The second thing, many questions similar these imply to me that many try to implement their own push-pull framework on top of RS instead of picking an existing implementation. Is my feeling right?

Yep! That's what led me to this thread.
