### ISSUE TITLE
Publisher activity before first request

### ISSUE THREAD

**Issue by davidmoten** [reactive-streams/reactive-streams-jvm#276]
I expect this question to be beyond the scope of reactive-streams-jvm but I thought I'd check.

In https://github.com/ReactiveX/RxJava/issues/3044 I was curious to know what is desirable in terms of activity of a `Publisher` after being subscribed but before the first request.  In RxJava a lot of what are effectively `Publisher`s make requests of other `Publisher`s and start buffering signals on subscription before any request is made of them.  Any thoughts on the desirability/importance of this?

**Comment by viktorklang** [comment]
I'm not 100% I understand the question but I'll take a stab at it anyway:

Requestion from upstream -before- any demand is signalled from downstream is a kind of "bet", and it means having to buffer until there is any demand coming in from the downstream, so it becomes a potential "warmup" optimization. And as with all optimizations, they should be made with hard evidence of efficacy.

Does that answer the question?

**Comment by agentgt** [comment]
I don't know if I should file this as a separate issue but I too was wondering more specifically if `Publisher.subscribe` should return in a *timely manner*.

The specification does not indicate so I can't decide to preallocate resources on the initial `Publisher.subscribe` or wait for `Subscription.request`. While it seems obvious to defer (instead of potentially blocking subscribe) its actually fairly difficult with RxJava 1.0 (well it shouldn't be but it is for the resource I'm using).

**Comment by viktorklang** [comment]
@agentgt Apologies for the delayed response (colds can be such a major hassle). There's typically a bit of work to do in `subscribe` to construct and set up the data generator (Subscription), and the method won't block the Subscriber (since the Subscriber is separate).

Is the `subscribeOn` analogous to `someExecutor.execute(() -> { publisher.subscribe(subscriber) })` in the case you want to defer that for someone "else" to execute?

**Comment by agentgt** [comment]
Yes I believe so. Basically its analogous to the whole `RejectedExecutionException` that is thrown when scheduling on a ExecutorService which I believe is fail fast (although fast ironically is a misnomer here because it could block).

It appears after looking at the spec again **Rule 1.9** provides an answer. If I'm acquiring resources its likely that I will throw an exception on failure (usually a checked one like IOException) thus `Publisher.subscribe` should return in a timely manner since only NPE can be thrown. 

Unfortunately (or maybe fortunately) this means when a caller asks to subscribe there is no direct way of saying hey publisher if your going to take a long time acquiring resources I want you to run in this thread and/or have this timeout etc. but that could be easily provided by a specific implementation (ie on retrieval of the `Publisher` and or extending the `Publisher` interface by a specific implementation).

Thus I think I have my answer.

**Comment by viktorklang** [comment]
@agentgt 

>Yes I believe so. Basically its analogous to the whole RejectedExecutionException that is thrown when scheduling on a ExecutorService which I believe is fail fast (although fast ironically is a misnomer here because it could block).

Even worse, the `CallerRunsPolicy` silently discards `Runnable`s which are submitted while the `ExecutorService` is shutting down. :scream:

>It appears after looking at the spec again Rule 1.9 provides an answer. If I'm acquiring resources its likely that I will throw an exception on failure (usually a checked one like IOException) thus Publisher.subscribe should return in a timely manner since only NPE can be thrown.

That's a well-reasoned conclusion if I ever saw one! :smile_cat: 

>Unfortunately (or maybe fortunately) this means when a caller asks to subscribe there is no direct way of saying hey publisher if your going to take a long time acquiring resources I want you to run in this thread and/or have this timeout etc. but that could be easily provided by a specific implementation (ie on retrieval of the Publisher and or extending the Publisher interface by a specific implementation).

Yes, this is possible to add both as an extension of Publisher to add something like `subscribeWithin` or similar OR to implement on the thing which creates the Publisher, in the style of `something.createPublisherWithSubscriptionTimeout(5, SECONDS).subscribe(subscriber)`

>Thus I think I have my answer.

Awesome. Thanks for your great questions and let us know how things work out!

Cheers,
√

**Comment by viktorklang** [comment]
Seems we can close this?
