### ISSUE TITLE
Say how many elements were collected in Latch.expectClose

### ISSUE THREAD

**Issue by jroper** [reactive-streams/reactive-streams-jvm#279]
It would be nice if when Latch.expectClose failed a test, it said how many elements it collected.  Currently it just says `Expected 10 elements to be drained within 2000 ms`.  This would help issues where failures can't be reproduced locally, but do happen in CI, for example, as it would point to whether the problem occurred in the subscription, or in the completion of the stream.

**Comment by ktoso** [comment]
Thanks, valid point - we can improve there.

So *that* `Latch` is always an 1-element-countdownlatch, it's just awaiting completion. The ticket is more about improving the error message signalled by `stochastic_spec103_mustSignalOnMethodsSequentially` it seems to me, right (agree it can be improved).

**Comment by jroper** [comment]
You're right, I hadn't noticed that.  So it seems the stochastic test isn't actually checking that 10 elements were received, it's just checking that the channel was closed.  It would be convenient if it said how many were received.

**Comment by ktoso** [comment]
Right, the actual failure this test is trying to expose is `"Illegal concurrent access detected"`, so that's not what you're hitting. It seems weird that you're hitting the latch timeout actually, since it's rather generous, but maybe CI is being really slow hm.

I updated the error message a bit so it should be more helpful.
For tweaking timeouts for CI envs there's some docs about it here: https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck#timeout-configuration

**Comment by jroper** [comment]
Well I actually think it's a legitimate bug in my code, not a timeout issue. That's why I want to know how many elements it produced, so I can know if I should be looking for the bug at the start, mid or end of the steam.

**Comment by ktoso** [comment]
Resolved in https://github.com/reactive-streams/reactive-streams-jvm/pull/281
