### ISSUE TITLE
What if onNext throws an exception. What is the publisher's responsibilities?

### ISSUE THREAD

**Issue by RichardHightower** [reactive-streams/reactive-streams-jvm#297]
What if onNext throws an exception. What is the publisher's responsibilities?

**Comment by viktorklang** [comment]
Hi Richard,

That is governed by 2:13:

"Calling onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way for a Subscriber to signal failure is by cancelling its Subscription. *In the case that this rule is violated, any associated Subscription to the Subscriber MUST be considered as cancelled, and the caller MUST raise this error condition in a fashion that is adequate for the runtime environment.*"

**Comment by RichardHightower** [comment]
Cool. I missed it. Nice. did my first (of many) implementation of reactive streams spec. 100 M TPS. (one pub, one sub). Fun stuff. I will need to run it though the TCK. Early days. Trying to wrap my head around and see how it fits in.

**Comment by viktorklang** [comment]
Great to hear, Richard.

The examples section of the repository includes some pretty decently
documented ones.

-- 
Cheers,
√

**Comment by RichardHightower** [comment]
QBit has two implementations so far. I plan on five.
eventually, i want to add streams as a alternative for callback. (A callback in qbit is like a Handler in Vertx or an Observable in RxJava or a Promise or AsyncFuture.. , but it is also an async Future and can be used for async calls or blocking calls.)
not all the time, but some time.
so if you are talking to a downstream stream, you can return pieces of the response at a time (at the service layer which then gets translated to websocket or a REST response).
a stream to me is sort of like a callback but instead of a singe response, it has many, and when it is all done, it get a done call or the other side can cancel. so I needed something like this in QBit anyway, and figured I would use a standard interface instead of rolling my own. Early days. https://github.com/advantageous/qbit

**Comment by gregw** [comment]
@viktorklang for what it is worth, I find the 2:13 clause overly prescriptive and  poorly worded. It was probably the cause of the long issue discussion we previously had regarding error handling.

I think that the restriction to just NPE is too strict.   At the very least it should allow a IllegalStateException if onNext is called when an appropriate request(n) has not been.     I also think that IllegalArgumentException makes sense in some respects, but accept that one is a slippery slope towards general error handling.

The I think the wording should be changed, as the "In the case that this rule is violated, ..." structure is confusing.   I think it would read better if it were changes to "SHOULD return normally....  but in the case that an exception is throw,.....".

However, apart from these quibbles, I do now accept the basic points you made about error handling.  

cheers

**Comment by viktorklang** [comment]
@gregw My sincere apologies for the delayed response here, including 2:13 for reference:

~~~
Calling onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way for a Subscriber to signal failure is by cancelling its Subscription. In the case that this rule is violated, any associated Subscription to the Subscriber MUST be considered as cancelled, and the caller MUST raise this error condition in a fashion that is adequate for the runtime environment.
~~~

>@viktorklang for what it is worth, I find the 2:13 clause overly prescriptive and poorly worded. It was probably the cause of the long issue discussion we previously had regarding error handling.

>I think that the restriction to just NPE is too strict. At the very least it should allow a IllegalStateException if onNext is called when an appropriate request(n) has not been. I also think that IllegalArgumentException makes sense in some respects, but accept that one is a slippery slope towards general error handling.

I can definitely see how one could make that argument, and conclusion. Worth noting is that there is an *inherent* race-condition between `request(n)` and `onNext` such that your proposal would only make deterministic sense for *synchronous* `Subscriber`s paired with *synchronously observable* `Subscription`s. The *TCK* already validates that `onNext` is only called for as many elements are `request`:ed so compliant implementations, which should pass the *TCK*, won't observe any non `NullPointerException`s.

The *sole* reason for allowing the `NullPointerException` to be thrown is because Java's type system is not sophisticated enough to express non-nullness of references. And in this case it ought to be safe for the `Publisher` to deal with the fact that *it* broke the expectation of the recipient. In the case that some other exception would be thrown by the `onX` methods—how would we know what we would do?
There was a *loooooong* discussion about "What to do if the onX methods throw exceptions" back in the day, I bet @benjchristensen remembers it as fondly as I do. :)


>The I think the wording should be changed, as the "In the case that this rule is violated, ..." structure is confusing. I think it would read better if it were changes to "SHOULD return normally.... but in the case that an exception is throw,.....".

I agree. That would be cleaner and more to the point. Perhaps a good, backwards-compatible, change to make for 1.0.1?

>However, apart from these quibbles, I do now accept the basic points you made about error handling.

Thank you. Are there any residual, more advanced points which remain unresolved there?
