### ISSUE TITLE
Merge Rules: Subscription 10 and Subscription 11

### ISSUE THREAD

**Issue by artem-zinnatullin** [reactive-streams/reactive-streams-jvm#360]
Rules [3.10](https://github.com/reactive-streams/reactive-streams-jvm/tree/a570a7f88a922752ed35ee28322db9f23e740ae6#3.10) and [3.11](https://github.com/reactive-streams/reactive-streams-jvm/tree/a570a7f88a922752ed35ee28322db9f23e740ae6#3.11) are **very** similar to each other, their explanations are exact same, looks like they could be merged into one rule:

>While the Subscription is not cancelled, Subscription.request(long n) MAY synchronously call onNext, *onComplete or onError* on this (or other) subscriber(s). 

I'll create a PR if this change will be approved.

**Comment by ktoso** [comment]
I'm not really in favour of this rewording... Seems a bit too change-for-change's sake.
It boils down to a preference thing - some may like "all info in one rule" while others "very small and simple piece-by-piece rules."

Summing up: I don't think a significant simplification would be gained by this rephrasing, thus I would rather stick to keeping the current wording.

If more contributors vote to do the change though, please do remember that TCK must be then amended to reflect this - if we shift numbering then *all* `n > #10` rules would be affected by the renumbering. It would also impact links to rules on the README - which implementations may have linked to, which could become confusing. So one more point why I don't think the gain is quite enough to apply this rephrasing.

**Comment by artem-zinnatullin** [comment]
>Seems a bit too change-for-change's sake.

I understand that point, but try to think about it from "first-time reader" perspective. Such small "inaccuracies" make reader think of possible options that may break rule, or improve wording, open an issue/PR instead of just reading the specification.

I must say, that most of the specification is very well written and descriptions under each rule help a lot and do not cause such thinking process described above, you just want to read rules and combine them into specification in your head.

>The change however, does come with costs - which I'll explain below.

> if we shift numbering then all n > #10 rules would be affected by the renumbering.

>So one more point why I don't think the gain is quite enough to apply this rephrasing.

That is actually second reason why I decided to open this issue, very glad that you brought it to discussion!

Current scheme of referencing and numbering in the rules does not allow additions, deletions or reordering of a rule without updating other references in the implementations (RxJava, Akka, Reactor, etc) which will make future changes in the Specification harder than it should be. 

Few possible solutions:

* Switch to one time generated hash based identifiers: `sha1(rule.firstVariantOfTheText())`
* Make sure all references include version of the specification itself: `v1.0.0 3.10` (same is possible for links).

What do you think about that? I can extract this into separate issue and link it to this one if you want.

**Comment by ktoso** [comment]
I'm sorry, but I think this is an overly dramatized perspective.

For one thing, this spec is *not* meant to change around. Simple changes we could do, *if* they provide enough value. The current numbering system does not lock us into anything, it is a hassle though. Your proposal would not solve this, it induces the same hassle on all implementations - they'd need to change stuff, and it goes into the a-bit-too-smart field as well, I would stray away from such solutions. RFCs and other specs remain with simple numbering, so let's stick to that too.

Back to the value of this proposal though:

> I understand that point, but try to think about it from "first-time reader" perspective. Such small "inaccuracies" make reader think of possible options that may break rule, or improve wording, open an issue/PR instead of just reading the specification.

I strongly disagree with the use of the word "inaccuracies" here. It is not inaccurate. The spec absolutely covers all bases here, it simply chose to do so in 2 rules, since we talk about happy-path and terminal-signals separately. It is only IMHO a matter of taste how to spell this out, thus the change would induce additional work / changes to existing implementations and documentation, without really making anything objectively simpler - it is not a rule simplification after all.

// I will be offline the next week or so, moving countries, please forgive my slow or lack-thereof replies over the next weeks.

**Comment by akarnokd** [comment]
The separation of 3.10 and 3.11 is fine because the interaction between a terminating `Subscriber` and `Subscription` is delicate and needs to be addressed separately: see §2.9 and §2.10.

**Comment by artem-zinnatullin** [comment]
>I strongly disagree with the use of the word "inaccuracies" here. It is not inaccurate. The spec absolutely covers all bases here

I messed up comment with anouther issue I created 😞, "inaccuracy" was about "calling thread" in #361.

@akarnokd good point!

Ok, issue seems to be resolved then, thanks!
