### ISSUE TITLE
TCK: optional_spec111_maySupportMultiSubscribe passed with reference drop

### ISSUE THREAD

**Issue by egetman** [reactive-streams/reactive-streams-jvm#371]
Hi, the case is:
when optional_spec111_maySupportMultiSubscribe validating subscriptions via:  

```java
        ManualSubscriber<T> sub1 = env.newManualSubscriber(pub);
        ManualSubscriber<T> sub2 = env.newManualSubscriber(pub);

        env.verifyNoAsyncErrors();
```

it simply ignore, if the publisher drop the first reference and use the second one.
So, the test will be passed even if publisher support single subscription.
Is it ok?

As an option, the check could be updated to validate the passed references in the 
end (like in required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber).

**Comment by ktoso** [comment]
Completely dropping a subscription is the worst thing an implementation could do - you'd leave the other side "hanging" waiting for a signal back from the publisher.

Instead of checking if the subscription is dropped (which is a rather ugly check), perhaps we can improve this by attempting to request and receive at least one element by the subscribers. Since this is an optional spec, failure will cause a skipped which is fine.

Edge cases would be if the Publisher is like a "first come first serve" and only is able to emit 1 element, so only one of the downstreams would receive an element. Perhaps a good improvement would then be to make this spec require a Publisher that can emit at least 2 elements, then (perhaps, we're not 100 sure about actual impl still), more implementations are likely to pass this test.

I would suggest adding an additional test in the style like I explained above and keep the current one as it is the simplest case of "does not signal errors or blows up when 2 subscribers come in", which is also good to test, and independent of signal emission style it has. The additional test would be useful. Feel free to submit a PR if you'd like to?

**Comment by ktoso** [comment]
Related, rule 1.9 talks about signaling errors in case it would not support 2 subscribers: "[...] for all other situations the only legal way to signal failure (or reject the Subscriber) is by calling onError (after calling onSubscribe)." so dropping is not legal. 

Though I wonder if it really adds more _real_ confidence that it handles the subscribers "properly", the test with actually signaling an element seems more useful in confirming it really supports them.

**Comment by egetman** [comment]
```
The additional test would be useful. Feel free to submit a PR if you'd like to?
```
Sure, i'll do it on the weekend.

**Comment by viktorklang** [comment]
Dropping Subscriber in `subscribe` would, as @ktoso points out, be illegal.

**Comment by egetman** [comment]
#376 done.
