### ISSUE TITLE
Question - why is submit(T element) not part of a Publisher?

### ISSUE THREAD

**Issue by asgs** [reactive-streams/reactive-streams-jvm#396]
I wonder why the `Publisher` interface doesn't provide a contract for `publish`ing or `submit`ing an event or an element of stream data.

The current JDK implementation of this interface has a class called `SubmissionPublisher` which does have a method to `submit` an element (and also a blocking variant called `offer`), but then the client code which wants to submit an event can't be oblivious to the kind of Publisher it's interacting with. I don't know what fundamentals I'm missing, but it looks to me that this breaks the "coding to interfaces" principle. Please enlighten.

**Comment by akarnokd** [comment]
Having a `submit`-like method call is part of the `Processor` interface in the form of `onNext`. Plain `Publisher`s are considered to be generators of events which, in its simplest form, can happen due to call to `subscribe()`. 

Different types of `Publisher` implementations may allow external stimulus, such as a `submit`, but mandating that all `Publisher`s do it is non-workable. For example, let's see a `Publisher` that upon subscription, emits the values from 0 to 100 and then completes. Where would a `submit()` come into play in this case?

**Comment by asgs** [comment]
To answer your question, it would still make sense to have a `submit(T item)` to do just that, while the client code controlling the publisher would do a `source.stream().forEach(publisher::subscribe)`, streaming each number till the end. Because, IIUC, a publisher is supposed to produce a stream of `T`-like values. My view is that the current definition of Publisher is it can only know about who its subscribers are, but not that it publishes anything at all and it's an **implementation-specific** detail. I find that hard to digest.

And what about dependency-inversion here? it's just not possible as it stands now.

**Comment by akarnokd** [comment]
You can express that via a `Publisher` that takes the `Stream` directly and runs a delimited `forEach` over it internally. See [this](https://github.com/akarnokd/Reactive4JavaFlow/blob/master/src/main/java/hu/akarnokd/reactive4javaflow/impl/operators/FolyamStream.java) for example that doesn't need any `submit` method to exist.

A main property of Reactive-Streams is the **non-blocking backpressure** it mandates, which is not possible with `submit` that actually [blocks](http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/SubmissionPublisher.java?revision=1.71&view=markup) if the `Subscriber` is not ready to receive:

```java
    /*
     * Publishes the given item to each current subscriber by
     * asynchronously invoking its {@link Flow.Subscriber#onNext(Object)
     * onNext} method, blocking uninterruptibly while resources for any
     * subscriber are unavailable.
     */
```

**Comment by asgs** [comment]
Ah, I think I get it now. The Publisher shouldn't block waiting for subscribers to become available, so what it does is takes the event source (from the client) and hands it over to the `Subscription` which has a MQueue like Datastructure to stream the source to the subscribers.

**Comment by rkuhn** [comment]
@asgs The Publisher interface is a set of functions and semantics that allows any entity that wants to emit data elements over an asynchronous boundary to speak to a matching Subscriber. It is not in any way descriptive nor should it be prescriptive for the entity itself or how the data come into existence.

On another note, the Reactive Streams specification and interfaces are not meant as end-user API, as witnessed by the enormous ratio of specification text to method count. SubmissionPublisher, on the other hand, is end-user API since it is readily usable without understanding all details of the spec.

**Comment by akarnokd** [comment]
@asgs Let me offer you another example. 

There is a `Publisher<Image>` that when subscribed to, the `Subscriber` receives images from a service on the internet. There is no way you could call `submit(Image)` because you don't have the images locally and upfront; the images can only come from the network. The service that sends the images can't call `submit()` on your instance because it is on a different machine altogether. 

In addition, it is possible you have two `Subscriber`s to this `Publisher<Image>` offset by time and both of them should be receiving all images. If the `subscribe` call triggers network connection to the server, two calls can trigger two independent network connections that get you the images at different pace and different time.

In addition to @rkuhn's explanation, the `SubmissionPublisher` was added as a convenience to bridge the non-reactive and possibly blocking world with the reactive and backpressured world.

**Comment by asgs** [comment]
@rkuhn so Reactive Streams Interfaces are targeted at library/framework builders rather than business application builders and that makes sense.

Another question (that may look stupid, but I have to ask) is if the Publisher is agnostic of the details of its source, what's wrong in decoupling the `subscribe` from a `Publisher` and instead let the `Subscriber`s register their source (Publisher) with the `Subscription`? I don't see why a Publisher needs to be aware of its clients at all and if `Subscription` is the real bridge that connects these two, it should be the one to worry about the order of the messages produced/consumed and the blocking/non-blocking nature of message flow. I know it sounds a good topic of discussion on Message Queues and has zero to do with Reactive Systems design, but this paves a way for Producer to be independent and only worry about producing data to `Subscription`s.

**Comment by rkuhn** [comment]
@asgs A Publisher is indeed just a factory for Subscriptions, where the Subscription is the handle that the Subscriber uses to communicate demand and cancellation upstream. In fact, the Publisher interface may be independent from the actual data production, as is frequently the case in RxJava cold Observables. In Akka Streams, however, the Publisher and Subscription point both to the same Actor, who governs the full stream lifecycle. These very different uses are permitted by the spec, which I think is the reason for its success.

**Comment by akarnokd** [comment]
If the `Subscriber` creates the `Subscription` instance, the `Publisher` can't react to requests and cancellation. It would need the `Publisher` to register callbacks on the `Subscription` so it can react to them. However, if the `Publisher` creates a `Subscription`, it can present an implementation to the `Subscriber` so that the `request()` and `cancel()` methods are practically those callbacks from the previous sentence.

**Comment by asgs** [comment]
@akarnokd  Guess I missed the part about "demand/supply" in the Specifications. Let me go read that firat.

Thanks to both of you for your time and the help offered! Much appreciated.

**Comment by rkuhn** [comment]
Thanks, also to @akarnokd for answering the respective other side of the coin :-)
