### ISSUE TITLE
Little bug in spec?

### ISSUE THREAD

**Issue by guenhter** [reactive-streams/reactive-streams-jvm#397]
Maybe it's the lack of may english but is is possible, that there is a little bug in the spec:

> 3.8 While the Subscription is not cancelled, Subscription.request(long n) MUST register the given number of additional elements to be produced to the respective subscriber.

Shouldn't the last word be `publisher` instead of `subscriber`?

> 3.8 While the Subscription is not cancelled, Subscription.request(long n) MUST register the given number of additional elements to be produced to the respective publisher.

Please bare with me in case I just didn't get the correct meaning of the sentence.

**Comment by ktoso** [comment]
Thanks for the issue :)
Better to ask and clarify than remain confused.

I believe the wording is correct. Notice the “to the respective” wording before the last word. 
In other words, we specify here that given a publisher that can handle multiple subscriptions, the requested amount of elements is “from a specific subscriber”. In other words, if you have S1 and S2, S1 did not request anything, but S2 did, then it’s OK to signal that number of elements to S2, however it’s NOT ok to signal anything to S1 yet since it did not signal any request (“signal any demand”).

**Comment by guenhter** [comment]
Ah, got it. I understood it that way, that the `publisher` must register the number of elements to produce.

So everything alright. Thanks for clarification.
