### ISSUE TITLE
JDK9 artifact/converter naming

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams-jvm#401]
Hey,

so we just now merged the "final bits" for the JDK9 Flow bridge/adapter jar as well as the TCK for java.util.concurrent.Flow.

Now, there are some open questions that we need to lock down now, before we cut the releases:

  1. Naming conventions on converters:
   Current scheme: toX (toSubscriber, toPublisher, toProcessor) and toFlowX (toFlowSubsriber, toFlowPublisher, toFlowProcessor)
   Current rationale: harmonizes with the types: X and Flow.X
  2. Naming of converter class.
   Current name: The converters are currently located in a class named `org.reactivestreams.ReactiveStreamsFlowBridge`
  3. Naming of converter jar
   Current artifact name is `reactive-streams-flow-bridge`
   Current rationale: it is intended to bridge implementations in both directions

@reactive-streams/contributors I'd like for us to settle the naming swiftly and with resolve (can we aim for within a week?), so if you have counter proposals, please speak now of forever hold your peace. :)

**Comment by viktorklang** [comment]
One possible proposal is:

1. keep toX, toFlowX
2. Rename converter class to `org.reactivestreams.Adapt`
3. Rename converter jar to `reactive-streams-flow-adapter`

**Comment by shenghaiyang** [comment]
Maybe like this? :)
```xml
<dependency>
  <groupId>org.reactivestreams</groupId>
  <artifactId>adapter-flow</artifactId>
</dependency>
```

**Comment by viktorklang** [comment]
@shenghaiyang All the other artifacts start with `reactive-streams` so it would seem asymmetric to change that. :)

**Comment by ktoso** [comment]
1. The `toPublisher` / `toFlowPublisher` are idea, it's good to have the name in there and that plays well with the Flow mnemonic, it's also short. The alternatives were with including "ReactiveStreams" or "RS" which is a bit weird.

2. In Java I'm usually a bit afraid to take "the good names" (`Adapt`), since conflicting in names is a pain in Java (no import renames like Scala etc). Those methods are likely to be used via a static import anyway I think, so the name does not matter too much. Sure it reads nice and fluently, but that's not really what this lib is about. Would rather use a boring name like `ReactiveStreamsAdapters` or something like that, also easier to find using autocompletion or searching-for-classname.

3. Module name sounds good, should align with the above, but that's likely good. `-adapters` I guess would be my preferred, it's not a single adapter, but each for each type. Other ideas would be `-compat` but that's perhaps meh, and does not really explain what exacly it is, so `-adapters` win AFAICS.

Hope this helps :)

**Comment by viktorklang** [comment]
@ktoso I agree with your point number 2. I'm fine with pluralizing adapter in the jarname.

**Comment by ktoso** [comment]
👍

**Comment by viktorklang** [comment]
@ktoso Would `org.reactivestreams.FlowAdapters` make sense?

**Comment by ktoso** [comment]
Nice idea, reads great 👍

**Comment by viktorklang** [comment]
@reactive-streams/contributors I created #402 as a concrete proposal of name changes. Please provide some counter proposals, or :+1:'s so we can ship the JDK9 TCK and interop pieces as soon as possible. (Would be nice with an RC1 within a week or so)

**Comment by viktorklang** [comment]
Closing as changes were merged without additional comments.
