### ISSUE TITLE
TCK should stress subscriber rule 2.5 in concurrent setting

### ISSUE THREAD

**Issue by ktoso** [reactive-streams/reactive-streams-jvm#427]
By now I have seen a number of talks where people present Reactive Streams / java.util.concurrent.Flow, and end up implementing their own non-compliant implementations. This, by itself, is not very good as it creates the false impression of trivialness of implementing these interfaces.

One common mistake seems to be forgetting about concurrency in the `Subscriber#onSubscribe` call, e.g. by naively implementing it like this: 

```java
            new Subscriber() {

              Subscription sub = null; // on purpose no volatile or any external synchronization

              @Override
              public void onSubscribe(Subscription s) {
               // this is racy, and we may accept (illegally?) multiple subscriptions
                if (this.sub == null) {
                  this.sub = s;
                  s.request(1);

// ...
```

This is racy, and may accept multiple subscriptions if called concurrently, yet almost all talks I've seen that present j.u.c.Flow do this mistake. While improving the TCK may not help those who do not use it, adding a test that exercises this case concurrently would be a good addition to the TCK.

I will submit a PR now.

**Comment by ktoso** [comment]
Reminder of the rule:

> 2.5 A Subscriber MUST call Subscription.cancel() on the given Subscription after an onSubscribe signal if it already has an active Subscription.

**Comment by akarnokd** [comment]
`onSubscribe` must be called sequentially and a `Publisher` should not call it more than once. We can only discourage reusing the same `Subscriber` with multiple `Publisher`s which may actually lead to such `onSubscribe` calls. I don't think we should actively defend against possible concurrent invocations of `onSubscribe`. 

Defending against synchronous multiple invocations may be reasonable, but unfortunately so far, it only created a lot of partial code coverage results. This is forcing me to actively test out such defenses, even though it was practically never a case when an RxJava operator was buggy in this regard - a missing call to `onSubscribe` was way more common in the early days.

The second problem is more like with `s.request(1)` followed by non-synchronized state manipulations which may end up interfering with a concurrent `onNext` invocation triggered by the request call. Deferring a request until `onSubscribe()` returns adds some overload and we generally don't do it in RxJava unless a `Subscriber` is an arbitrary Reactive Streams implementation (instead of our own `FlowableSubscriber`). In fact, this deferred requesting is mandated by the TCK currently as some tests fail reporting concurrent `onSubscribe`-`onNext` invocations.

There is, however, a situation where a race may occur with the upstream `Subscription`: when the `Subscriber` allows cancellation before `onSubscribe` is called. In RxJava terminology, this is a deferred cancellation situation often happening when multiple sources are involved in some fashion. There, atomics/synchronization is essential around setting that `Subscription` field.

**Comment by ktoso** [comment]
I guess it indeed may ride on Publisher side via 1.3

> onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled in a thread-safe manner—and if performed by multiple threads—use external synchronization.

in which case my point is moot. Would be fine with me as well; 

For what it's worth, our examples in the reactive-streams repo do guard from such concurrent access  (Akka Streams as well)

**Comment by akarnokd** [comment]
Well, it's definitely checking something mandatory that wasn't verified before, risking failures for implementations that passed 1.0.2. I'm confident §1.3 covers this case properly.

**Comment by ktoso** [comment]
Yeap, seems I needlessly followed the white rabbit into the rabbit hole this time around. 
Closing this, all good.
