### ISSUE TITLE
Where to find working examples

### ISSUE THREAD

**Issue by ilyas2016** [reactive-streams/reactive-streams-jvm#439]
I am very interested to work on reactive stream specially on java.
I would like to fully understand how to use it.

can you please provide some material with example so i learn reactive streams from scratch.

thanks

**Comment by mahibabar** [comment]
RxJava Callable would be a good starting point.

**Comment by viktorklang** [comment]
@ilyas2016 There's an example directory in the basefolder of this repository: https://github.com/reactive-streams/reactive-streams-jvm/tree/master/examples

Depending how you perfer to learn, there are YouTube videos, you can read the spec, the TCK, you can read any of the RS implementations, or you can start using any of them in combination.

I'll close this Issue since it really isn't an Issue—have fun learning RS!

Cheers,
√
